### ISSUE TITLE
Windows builds, please!

### ISSUE THREAD

**Issue by DI555** [tx00100xt/SeriousSamAlphaRemake#1]
Could it be possible to provide and Windows builds of SeriousSamAlfaRemake either, 32 and 64 bits, please!
It could get much more popularity to the game!

**Comment by tx00100xt** [comment]
Added support for Windows.
You can download the build in the releases section:

https://github.com/tx00100xt/SeriousSamAlphaRemake/releases/tag/v1.5.1

**Comment by DI555** [comment]
Great news!!!
am i think wright - any installed mod like alfa or xplus - will work and will take effect only on current client side in multyplaying ?

**Comment by tx00100xt** [comment]
Almost all modifications have multiplayer support. Alpha remake have multiplayer support.
